// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBRbnAvP7IZ8ZxMx_jV7r24W7NZmG5qEI',
    appId: '1:893294498703:web:f238358681f9b5eb9271fa',
    messagingSenderId: '893294498703',
    projectId: 'cards-d8d71',
    authDomain: 'cards-d8d71.firebaseapp.com',
    storageBucket: 'cards-d8d71.appspot.com',
    measurementId: 'G-8GCGS2R18M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYu8a3owNsBmlnHf4YHHlWkgUCVOICecc',
    appId: '1:893294498703:android:734bbbf9be8ea3369271fa',
    messagingSenderId: '893294498703',
    projectId: 'cards-d8d71',
    storageBucket: 'cards-d8d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMoyVsb0E1Mkgs-11NNByiLN_5MzA3RIY',
    appId: '1:893294498703:ios:5869b62d66758aac9271fa',
    messagingSenderId: '893294498703',
    projectId: 'cards-d8d71',
    storageBucket: 'cards-d8d71.appspot.com',
    iosBundleId: 'com.example.cards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMoyVsb0E1Mkgs-11NNByiLN_5MzA3RIY',
    appId: '1:893294498703:ios:fe63c5b85719f5fc9271fa',
    messagingSenderId: '893294498703',
    projectId: 'cards-d8d71',
    storageBucket: 'cards-d8d71.appspot.com',
    iosBundleId: 'com.example.cards.RunnerTests',
  );
}
